# File to disable some offences of rubocop linter

Style/Encoding:
  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/*'
          